services:
  suporte704-api:
    container_name: suporte704-api
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT}:3300" 
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.suporte704-api.rule=Host(`api.suporte704.com.br`)
      - traefik.http.routers.suporte704-api.rule=Host(`teste.suporte704.com.br`)
      - traefik.http.routers.suporte704-api.entrypoints=web
      - traefik.http.services.suporte704-api.loadbalancer.server.port=80     
      
networks:
  dokploy-network:
    external: true

